### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by DmitryPR** [vinivendra/metal-metaballs#6]
Hello, any plans to port this to swift 3?

**Comment by vinivendra** [comment]
Hey! It's been a long time since I've played around with this code, but it shouldn't be too hard to port it actually. If nostalgia hits, I might just do it today or tomorrow 😄
Are you interested in it?

**Comment by DmitryPR** [comment]
Yes, would be nice to see this on Swift 3. Are you planning to support this and add a cocoapods components in the future?

**Comment by vinivendra** [comment]
Support Swift 3? Definitely. To be honest, I thought I had already done it in Swift 3, but I guess not.
Make it available through cocoapods? I'd have to think about that a bit... it would envolve restructuring a bit of the API and then learning to interact with cocoapods, but it shouldn't be too much work. So yeah, probably.

**Comment by vinivendra** [comment]
There's a branch `feature-swift3` if you wanna keep up with the work. The code should already be working in swift 3, even though it still looks kinda ugly and throws a lot of warnings around.

**Comment by vinivendra** [comment]
Wow, that was a lot easier than I expected. Both `dev` and `master` are now in swift 3 :)
I'll try to keep the issues organized, so I'm closing this one and opening #7 to track Cocoapods support. Since that requires an update to the API anyhow, it might be interesting to add Swift Package support too 🤔
